[tasks.build_scss]
description = "Convert scss in css"
install_script = '''
if ! $(rsass --help 1> /dev/null)
then
    cargo install rsass --features=commandline
fi
'''
script = '''
mkdir -p ../static/css/
rsass --style Compressed scss/cam_bot.scss > ../static/css/cam_bot.css
'''

[tasks.wasm_build]
description = "Build front"
dependencies = ["build", "build_scss"]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "cam_bot", "--dev", "--out-dir", "../static/wasm/"]

[tasks.serve_]
description = "Tasks request when serve is call"
dependencies = ["build_scss", "wasm_build", "clippy", "format", "build"]
